# Generated by Django 3.1.7 on 2022-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20220531_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
