# Generated by Django 3.1.7 on 2022-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20220525_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='focal_point',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='kpi',
            field=models.TextField(),
        ),
    ]
